// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://scfgumncqqzqexqahqqf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNjZmd1bW5jcXF6cWV4cWFocXFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMDE5NTUsImV4cCI6MjA2NTY3Nzk1NX0.wWXXmP_uyoCThIk1yTuiDYQdpXa4IqkdiOlRI3lFm64";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);